### PR TITLE
Convert all years to leap years

### PR DESCRIPTION
**Pull request by huaracheguarache**
This PR consists of two commits:

- The first one removes some de-duplication code that is not needed due to `nv=0` already being selected in the data. I've checked to be sure that this doesn't remove any attributes from the data.

- The second one deals with the issue of leap years. The approach I've chosen is to convert all years to leap years and to fill February 29th with data interpolated between February 28th and March 1st for non-leap years.

### CODE REVIEW

**Comment by huaracheguarache** [comment]
Hold on, I've made a mistake here with the indexing.

**Comment by epifanio** [comment]
thanks!

**Comment by huaracheguarache** [comment]
Could you please revert the merge of this PR? I should have closed it since I ended up using a different solution than converting all the years to leap years. Sorry about that!

**Comment by epifanio** [comment]
> 

no problem, changes reverted

**Pull request merged**
